apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: shadows.burghardt.tech
spec:
  group: burghardt.tech
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                podName:
                  type: string
  names:
    kind: Shadow
    plural: shadows
  scope: Namespaced